services:
  fe:
    container_name: ychat-fe
    restart: unless-stopped
    image: yphung282/ychat-fe-arm:latest
    ports:
      - $VITE_PORT:80
    env_file:
      - ./.env

  mongo:
    container_name: ychat-mongo
    restart: unless-stopped
    build: ./mongo-config/
    ports:
      - $MONGODB_PORT:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - $MONGODB_VOLUME_PATH:/data/db
    healthcheck:
      test: /docker-entrypoint-initdb.d/mongo-init.sh
      start_period: 10s
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ychat-network

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    ports:
      - $REDIS_PORT:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - $REDIS_VOLUME_PATH:/data
    networks:
      - ychat-network

  be:
    image: yphung282/ychat-be-arm:latest
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
    ports:
      - $PORT:$PORT
      - $WS_PORT:$WS_PORT
    env_file:
      - ./.env
    volumes:
      - ./secure:/app/secure
    networks:
      - ychat-network

networks:
  ychat-network:
    driver: bridge
